### PR TITLE
Fix for Gold Dust issues.

### LINKED ISSUE #3: Gold Dust can't be obtained more than once at certain locations.
Known locations that do not allow Gold Dust more than once:
* All Chests (rewards recovery heart instead)
* Postman HP (rewards purple rupee instead)
* Swordsman School HP (rewards red rupee instead)
* Lab Fish HP (rewards recovery heart instead i think)
* Dog Race HP (rewards red rupee instead)
* Keaton Quiz HP (reward red rupee instead)

### PR DESCRIPTION
**Pull request by ZoeyZolotova**
Change Goron Race Bottle to be just plain Gold Dust. Change Mountain Village Grotto (Spring) to contain Empty Bottle instead of Red Rupee. This allows Gold Dust to be recollectable anywhere without removing any bottles or causing any duplicate bottles. Add UpgradeBigBombBag to the REPEATABLE list so that it can be reacquired if necessary. Update Casual and Glitched logic to use the new Bottle instead of Goron Race Bottle.

Fixes #3

### CODE REVIEW

File: ItemSwap.cs [hunk 1]
```diff
@@ -184,11 +184,12 @@ public static void WriteNewItem(int ItemSlot, int NewItem, bool IsRepeatable, bo
                 WriteToROM(0xB499A6, (ushort)GetItemIndices[ItemSlot]);
                 WriteToROM(0xC72B5A, (ushort)GetItemIndices[ItemSlot]);
             };
-            if (NewItem == 14)
-            {
-                WriteToROM(0xB499B2, (ushort)GetItemIndices[ItemSlot]);
-                WriteToROM(0xC72B66, (ushort)GetItemIndices[ItemSlot]);
-            };
+            // Goron Race Bottle now rewards a regular Bottle, so this is unnecessary until a proper fix for Goron Dust is found.
```
Comment (zmarotrix) [inline ItemSwap.cs]: I would replace the Goron Race Bottle with the Gold Dust and have the new Bottle be a random item. This would make the logic more accurate.

Comment (ZoeyZolotova) [reply ItemSwap.cs]: Currently there's only one check in the logics that require Gold Dust. That is the Gilded Sword check. So I updated that check in Casual and Glitched logic files. Users with User Logic will need to update just that check to use Gold Dust instead of Goron Race Bottle.

If we do the opposite, i.e. replace Goron Race Bottle with Gold Dust, and Mountain Village Grotto (Spring) with a Bottle, then there are far more changes required to the logics, and users with User Logic will need to go through and update a lot of logic. Then if/when this issue is fixed properly, they'll need to go back and change them all back.

In my opinion, the way I've done it is the cleanest way.

Comment (ZoeyZolotova) [reply ItemSwap.cs]: Fixed the way you suggested. Updated logic.

File: Items.cs [hunk 2]
```diff
@@ -22,7 +22,7 @@ public class Items
         public const int ItemFairySword = 11;
         public const int ItemBottleWitch = 12;
         public const int ItemBottleAliens = 13;
-        public const int ItemBottleGoronRace = 14;
+        public const int ItemGoldDust = 14;
```
Comment (zmarotrix) [inline Items.cs]: Can we please add an annotate the original name?

File: Items.cs [hunk 3]
```diff
@@ -239,7 +239,7 @@ public class Items
         public const int ChestWellRightPurpleRupee = 206;
         public const int ChestWellLeftPurpleRupee = 207;
         public const int ChestMountainVillage = 208; //contents? 
-        public const int ChestMountainVillageGrotto = 209; //contents? 
+        public const int ChestMountainVillageGrottoBottle = 209;
```
Comment (zmarotrix) [inline Items.cs]: Annotate this one as well.
